repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        files: ".py"
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.0'
    hooks:
    -   id: mypy

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
        # Run the linter
    -   id: ruff
        types_or: [ python, jupyter ]
        args: [ --fix ]
        # Run the formatter
    -   id: ruff-format
        types_or: [ python, jupyter ]